In [12]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
df=pd.read_csv('movies_metadata.csv')
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [13]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [14]:
df=df[['title', 'overview','genres','tagline','popularity','vote_average']]

In [15]:
df.head()

,title,overview,genres,tagline,popularity,vote_average
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,21.946943,7.7
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,17.015539,6.9
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,11.7129,6.5
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,3.859495,6.1
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,8.387519,5.7

In [16]:
df.isnull().sum()

title               6
overview          954
genres              0
tagline         25054
popularity          5
vote_average        6
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(13)

In [18]:
df=df.drop_duplicates().reset_index(drop=True)

In [19]:
df.duplicated().sum()

np.int64(0)

In [22]:
df=df.dropna(subset=['title'])

In [24]:
df['overview']=df['overview'].fillna('')

In [26]:
df['tagline']=df['tagline'].fillna('')

In [27]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
popularity      0
vote_average    0
dtype: int64

In [28]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [30]:
import ast
df['genres']=df['genres'].apply(lambda x: " ".join(i['name'] for i in ast.literal_eval(x)))

In [31]:
df.head()

,title,overview,genres,tagline,popularity,vote_average
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,21.946943,7.7
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,17.015539,6.9
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,11.7129,6.5
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,3.859495,6.1
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,8.387519,5.7

In [32]:
df['tags']=df['overview']+" "+df['genres']+" "+df['tagline']

In [36]:
df['tags'][0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation Comedy Family "

In [37]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [38]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [39]:
stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()

In [40]:
def preprocess_text(text):
  text=text.lower()
  text = re.sub(r'[^a-zA-Z\s]', '', text)
  words = text.split()
  words = [word for word in words if word not in stop_words]
  words = [lemmatizer.lemmatize(word) for word in words]
  return " ".join(words)

In [41]:
df['tags']=df['tags'].apply(preprocess_text)

In [42]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [43]:
df=df.reset_index(drop=True)

In [44]:
indices=pd.Series(df.index,index=df['title']).drop_duplicates()

In [45]:
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(stop_words='english', max_features=50000, ngram_range=(1,2))
tfidf_matrix=tfidf.fit_transform(df['tags'])

In [57]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
def recommend_movies(title,n=10):
  if title not in indices:
    return["Moive Not Found"]
  idx=indices[title]
  sim_score=cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
  sim_index=sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[sim_index]

In [58]:
recommend_movies('Toy Story',5)

2996         Toy Story 2
15344        Toy Story 3
24512          Small Fry
28972    Superstar Goofy
17184          Group Sex
Name: title, dtype: object

In [59]:
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf,open('tfidf.pkl','wb'))

In [60]:
from google.colab import files

files_to_download = [
    '/content/tfidf.pkl',
    '/content/df.pkl',
    '/content/movies_metadata.csv',
    '/content/tfidf_matrix.pkl',
    '/content/indices.pkl'
]

for file_path in files_to_download:
    files.download(file_path)